# Generated by Django 4.0.2 on 2022-03-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productId', models.IntegerField(editable=False, null=True)),
                ('productName', models.CharField(max_length=255)),
                ('productPrize', models.CharField(max_length=255)),
                ('productImage', models.ImageField(upload_to='')),
                ('userId', models.IntegerField(editable=False)),
                ('userName', models.CharField(max_length=255)),
                ('userEmail', models.EmailField(max_length=255, null=True)),
                ('qty', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('order_json', models.TextField(max_length=5000)),
                ('userId', models.IntegerField(editable=False)),
                ('userName', models.CharField(max_length=255)),
                ('userEmail', models.EmailField(max_length=255, null=True)),
                ('userAddress', models.CharField(max_length=555, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('zip_code', models.IntegerField(null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('totalAmount', models.IntegerField(null=True)),
                ('paymentStatus', models.CharField(default='No', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('productDesc', models.TextField(max_length=1000, null=True)),
                ('productPrize', models.CharField(max_length=255)),
                ('productImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
