# Generated by Django 4.0.2 on 2022-02-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('productPrize', models.CharField(max_length=255)),
                ('productImage', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
