# Generated by Django 4.0.2 on 2022-03-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart_orderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('cID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentStatus',
            field=models.CharField(default='PENDING', max_length=255, null=True),
        ),
    ]
