# Generated by Django 4.0.2 on 2022-02-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
