# Generated by Django 4.0.2 on 2022-02-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_products_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
