# Generated by Django 4.0.2 on 2022-02-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('productPrize', models.CharField(max_length=255)),
                ('productImage', models.URLField()),
                ('userId', models.IntegerField(max_length=255)),
                ('userName', models.CharField(max_length=255)),
            ],
        ),
    ]
