# Generated by Django 4.0.2 on 2022-02-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='userEmail',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productImage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='userId',
            field=models.IntegerField(editable=False),
        ),
    ]
