# Generated by Django 4.0.2 on 2022-02-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cart_useremail_alter_cart_productimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='productId',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
